"""empty message

Revision ID: 2f299907c0cc
Revises: 
Create Date: 2021-10-24 23:32:07.177198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f299907c0cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('booking_token', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fly_from', sa.String(length=9), nullable=True),
    sa.Column('fly_to', sa.String(length=9), nullable=True),
    sa.UniqueConstraint('date', 'fly_from', 'fly_to', name='unique_ticket_date_fly_from_fly_to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
