"""empty message

Revision ID: 4160fd5c9b5c
Revises: 
Create Date: 2021-10-23 17:38:49.590781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4160fd5c9b5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('booking_token', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.UniqueConstraint('booking_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
