"""empty message

Revision ID: 5a618f289b23
Revises: d6b2fc28e054
Create Date: 2021-10-23 22:20:36.975282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a618f289b23'
down_revision = 'd6b2fc28e054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('fly_from', sa.String(length=9), nullable=True))
    op.add_column('ticket', sa.Column('fly_to', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'fly_to')
    op.drop_column('ticket', 'fly_from')
    # ### end Alembic commands ###
