"""empty message

Revision ID: d6b2fc28e054
Revises: 4160fd5c9b5c
Create Date: 2021-10-23 18:06:46.126210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b2fc28e054'
down_revision = '4160fd5c9b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date')
    # ### end Alembic commands ###
